({
    
    baseUrl: "js/classes",
    packages: [
        {
            name: 'jquery', 
            location: '../libs', 
            main:'jquery'
        }, 
        {
            name: 'underscore', 
            location: '../libs', 
            main:'underscore'
        }, 
        {
            name: 'backbone', 
            location: '../libs', 
            main:'backbone'
        }, 
        {
            name: 'less', 
            location: '../libs', 
            main:'less'
        },
        {
            name: 'hammer', 
            location: '../libs', 
            main: 'hammer'
        }, 
        {
            name: 'jquery.hammer', 
            location: '../libs', 
            main: 'jquery.hammer'
        }, 
        {
            name: 'youtube', 
            location: '../libs', 
            main: 'iframe_api'
        }, 
        /*{
            name: 'io', 
            location: 'http://' + window.location.hostname, 
            main: 'socket.io/socket.io.js'
        }, */
        {
            name: 'io', 
            location: 'http://' /*+ window.location.hostname + ':8800'*/, 
            main: 'socket.io/socket.io.js'
        }, 
        {
            name: 'leaflet', 
            location: "http://cdn.leafletjs.com/leaflet-0.7", 
            main: 'leaflet'
        }, 
        {
            name: 'leafletcss', 
            location: '../libs', 
            main: 'leafletcss'
        }, 
        {
            name: 'JSARToolkit', 
            location: '../libs', 
            main:'JSARToolKit'
        }, 
        {
            name: 'Three', 
            location: '../libs', 
            main: 'Three'
        }, 
        {
            name: 'Threex', 
            location: '../libs', 
            main: 'threex'
        }, 
        {
            name: 'shimRequestAnimationFrame', 
            location: '../libs', 
            main: 'shimRequestAnimationFrame'
        }, 
        {
            name: 'shimUserMedia', 
            location: '../libs', 
            main: 'shimUserMedia'
        }, 
        {
            name: 'require', 
            location: '../libs', 
            main: 'require'
        }, 
    ],
    shim : {
        underscore : 
        {
            exports:'_'
        }, 
        backbone: 
        {
          deps: ["underscore", "jquery"],
          exports: "Backbone"
        }, 
        Threex:{
            deps: ["Three", "JSARToolkit"], 
            exports: "Threex"
        }, 
        less: {            
            exports:'less'
        },
    },
    locale: "en-us",
    optimize: "none",

    //name: "main",
    include: ["./../main", 'AnimationForm', 'Block', 'BorderForm', 'Button', 'ButtonForm', 'ColorForm', 'ContentForm', 'Dialog', 'DrawingPage', 'Form', 'ImageBlock', 'Page', 'Panel', 'PublishForm', 'TextBlock', 'TextForm', 'TransformForm', 'VideoBlock'],
    //insertRequire: ['main'],
    out: "build/optimized-file.js",

    //In RequireJS 2.0, "out" can be a function. For single JS file
    //optimizations that are generated by calling requirejs.optimize(),
    //using an out function means the optimized contents are not written to
    //a file on disk, but instead pass to the out function:
    /*out: function (text) {
        //Do what you want with the optimized text here.
    },*/
})
